name: PHP Composer CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup PHP environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # Versi PHP yang sesuai
          extensions: ctype, curl, dom, fileinfo, filter, hash, json, libxml, mbstring, openssl, pcre, session, tokenizer, xml, xmlwriter
          ini-values: |
            memory_limit=-1
          coverage: none

      # Step 3: Validate PHP version and extensions
      - name: Check PHP platform requirements
        run: composer check-platform-reqs

      # Step 4: Install Composer dependencies
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-scripts

      # Step 5: Run additional Composer scripts (if any)
      # Uncomment the following lines if your `composer.json` has custom scripts
      # - name: Run Composer scripts
      #   run: composer run-script post-install-cmd
